### ISSUE TITLE
This is a spectacular tutorial series, is Part 3 in the works?

### ISSUE THREAD

**Issue by othyn** [mralexhay/ShortcutsExample#1]
This is a spectacular tutorial series for Shortcuts and one of the few good resources for Shortcuts that I could find on the web. I use ToolBox Pro and its awesome to see you being the one to impart this brilliant knowledge to the community.

Just wondering, is Part 3 in the works? As the custom types and app interaction touted to arrive in Part 3 would be amazing!

**Comment by mralexhay** [comment]
Thanks for the kind words and the reminder!

Part 3 is now [available](https://toolboxpro.app/blog/adding-shortcuts-to-an-app-part-three).

It looks at in-app intent handling, the visual list API, custom output types and supporting shortcuts using the SwiftUI app protocol.

I'm working on part 4 now which looks at returning data back to the main app from a Shortcuts action.
